### ISSUE TITLE
Lots of DNS queries on 1.6.2

### ISSUE THREAD

**Issue by Houtek** [raspiblitz/raspiblitz#1909] opened 2020-12-27 14:52 UTC
Reference: #1656

Hi, 
even with the latest 1.6.2 release I see a lot of DNS requests on my pihole coming from Raspiblitz.

![grafik](https://user-images.githubusercontent.com/12113170/103173432-39919c80-485b-11eb-8ea7-6f6b45efd99d.png)

I disabled the IPv6 address on the eth0 interface to make sure, that v6 is not the root cause.

Do you need more information? I'm glad, when I can help.

**Comment by Houtek** [comment] 2020-12-31 15:23
After I checked /etc/hosts and made sure, the hostname is set correctly, the queries went to normal. 
I'm not sure, which name is set during install, but this might be worth a view.

**Comment by rootzoll** [comment] 2021-01-04 22:32
@Houtek what was the correct way to set `/etc/hosts` ?

**Comment by Houtek** [comment] 2021-01-09 12:40
Ok, forget what I said earlier. It is still very chatty.

![grafik](https://user-images.githubusercontent.com/12113170/104091815-3c8b8480-5280-11eb-9b77-7479d73f84ce.png)


The only way I could get rid of the amount of queries was to install a local unbound as resolver. Since I don't have a spare RPi at the moment, I can't test the behavior with a brand new install.

**Comment by rootzoll** [comment] 2021-01-10 16:48
Please update your findings. Something to keep eye on - pushing this to a later realease.

**Comment by rschueler** [comment] 2021-02-07 12:07
I can see the same effect on my pihole. The in-addr.arpa PTR request are DNS reverse lookups and I identified the IPs to be peers connected to the bitcoin node. The domain names show the IPs in reverse order: 70.229.234.44.in-addr.arpa will show up as 44.234.229.70 in Bitcoin Explorer.
My guess is, that a process related to Bitcoin Core or Bitcoin Explorer tries to lookup the domain name of connected peers for logging purpose.

**Comment by PatrickScheich** [comment] 2021-02-13 21:43
the origin of these reverse DNS  requests is a call to `netstat -a` in file `\home.admin\config.scripts\bonus.electrs.sh` as this call will try to resolve all IP addresses found. 

Prevent this by using `netstat -an` 

i created a PR #2006

**Comment by rootzoll** [comment] 2021-03-23 20:55
The netstat PR is merged and will be part of v1.7RC1 for final testing.

**Comment by rootzoll** [comment] 2021-04-16 22:49
@PatrickScheich @Houtek any results on this with testing v1.7RC2 so far?
Image can be downloaded here: https://github.com/rootzoll/raspiblitz/tree/dev#downloading-the-software

**Comment by rootzoll** [comment] 2021-04-18 17:29
Because of time issues I was not able to setup a Pihole myself for testing .. so pushing this for final testing myself to v1.7.1

**Comment by PatrickScheich** [comment] 2021-04-19 19:08
> 
> 
> @PatrickScheich @Houtek any results on this with testing v1.7RC2 so far?
> Image can be downloaded here: https://github.com/rootzoll/raspiblitz/tree/dev#downloading-the-software

I have been a bit lazy lately
But I updated my raspiblitz yesterday, the dns request spam is perfectly gone in my environment
You can consider this test as passed

**Comment by rootzoll** [comment] 2021-04-20 20:03
Perfect :D thanks for testing .. closing issue.

**Comment by openoms** [comment] 2021-06-30 20:39
This was again reported to be an issue on v1.7 by a user running a pihole.
![image](https://user-images.githubusercontent.com/43343391/124028049-75184980-d9eb-11eb-829a-c458f75ce430.png)
![image](https://user-images.githubusercontent.com/43343391/124028102-83666580-d9eb-11eb-80a2-6dcb6ddd7be5.png)


not sure how mempool.space get pinged, it is likely from the app

**Comment by flyerbear** [comment] 2022-05-01 14:26
I wanted to add that I am seeing this behavior too - DNS queries to both v4.ipv6-test.com and mempool.space (since installing mempool space), every 12 seconds for each.

Since mempool space is self hosted are these queries really necessary?

I'm running raspiblitz v1.7.2 behind Tor. 

I reached out to the mempool.space guys on their keybase support chat and after some back and forth, they believe the issue is something with the raspiblitz code rather than their own. I added this comment to issue #2387 as well.

**Comment by rootzoll** [comment] 2022-05-17 19:29
TODO: When running electrs there is also a call to `internet.sh status global` which does trigger a call to v4.ipv6-test.com and gets periodically called for status information by the `00blitzInfo.sh`script:
https://github.com/rootzoll/raspiblitz/blob/78a0ae00a0581cbc1b3c54f7f2770db3f2d960c8/home.admin/config.scripts/bonus.electrs.sh#L24

**Closed as completed** 2022-12-15 13:55 UTC
