### ISSUE TITLE
zerotier broken on my raspiblitz

### ISSUE THREAD

**Issue by KainerW** [raspiblitz/raspiblitz#2850] opened 2021-12-25 12:31 UTC
Hi, maybe someone can help me here.

I can not get zerotier to work anymore, it stopped from one day to the other. 

Trying to activate it on the raspiblitz-menue I just get a screen with the error mesage "Zerotier join failed".

When I try this: sudo zerotier-cli join [my.zerotier-id]
I do get this:
/usr/sbin/zerotier-cli: 1: /usr/sbin/zerotier-cli: Syntax error: “(” unexpected

Any idea how to fix it or what might cause this error?

**Comment by openoms** [comment] 2021-12-25 22:23
haven't experienced this, but use:
`sudo zerotier-cli`
`--help` is the a useful option
and I use:
`sudo zerotier-cli status`
and
`sudo zerotier-cli listnetworks`
the most often.

**Comment by KainerW** [comment] 2021-12-26 10:08
THX Openoms. I tried but for each of this lines I get back: '/usr/sbin/zerotier-cli: 1: /usr/sbin/zerotier-cli: Syntax error: "(" unexpected'

**Comment by openoms** [comment] 2021-12-26 10:16
try to restart the node and maybe use another terminal to log in.

if that doesn't help:
try reinstalling zerotier from the menu or remove with:
`sudo apt uninstall zerotier`
 and follow the official download instructions from zerotier.com for Debian.

**Comment by KainerW** [comment] 2021-12-26 10:29
I tried this before. 'Sudo apt uninstall zerotier' does not work. It results in 'E: Invalid operation uninstall'. 

Using "sudo apt remove zerotier" results in:
Reading package lists... Error!
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/dpkg/status
E: The package lists or status file could not be parsed or opened.

Could I remove the status file and re-generate it somehow without destroying my installations on this blitz/pi?

**Comment by openoms** [comment] 2021-12-26 10:37
It is a weird problem.
can try
`sudo apt remove zerotier* --purge`

otherwise a reflash will solve this. Best to use a new SDcard so rule out the file corruption because of the card failing.

**Comment by KainerW** [comment] 2021-12-26 10:41
sudo apt remove zerotier* --purge gave:

Reading package lists... Error!
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/dpkg/status
E: The package lists or status file could not be parsed or opened.

Will try a reflash and report. Thank you.

**Comment by KainerW** [comment] 2021-12-27 11:08
I reflashed (and updated to 1.7.1) a new sd card - zerotier finally worked after restarting the node 3-4 times finally. 

... But now all but one other apps are broken. Only app still working is specter. Sphinx broke, thunderhub broke, mempool broke. Very frustrating.

**Comment by openoms** [comment] 2021-12-27 12:47
Without details nothing can be done.

Look at the output of:
`debug`
yourself and can post a link of the uploaded logs.
Find the command at the end of the debug output.

**Comment by KainerW** [comment] 2021-12-27 13:46
Thank you! -> https://termbin.com/0aa0

Update so far: I have restarted the node about 10-20 times, I have tried/made all updates of all apps via raspi-menu, changed nothing.
Had then to manually delete mempool app and install new to make this app work. THIS fixed mempool-app eventually. 
Same did work for thunderhub - but: I had to try to install it 5 times. 4 times I got error message, then it finally worked.
Sphinx chat app still broken and not working, deinstalled many times, reinstalled many times, updated many times, restarted node many times. still not working.  Maybe you can see what is wrong in the logfile?

**Comment by openoms** [comment] 2021-12-27 14:31
your bitcoind and LND working normally. Can't see the reason for other apps breaking (the logs are not log enough.)

Definitely shouldn't need to restart the node or reinstall apps and this doesn't happen with others, neither I could reproduce.

Did you use a new SDcard when reflashed?
Something has corrupted your system to start with.

You can see get the logs of the individual services in the SYSTEM menu.
eg. for sphinxrelay.

**Comment by KainerW** [comment] 2021-12-27 14:40
Used a new SDcard yes. 
I might get a new pi/hdd as this one seems to be broken/unreliable.

**Comment by openoms** [comment] 2022-01-02 00:50
closing as the original issue is fixed

**Closed as completed by openoms** 2022-01-02 00:50 UTC
