### ISSUE TITLE
CL seed not appears from menu after recovering

### ISSUE THREAD

**Issue by Tracachang** [raspiblitz/raspiblitz#2839] opened 2021-12-22 19:09 UTC
When creating a new CL wallet, seed can be seen from CL menu -> Seed.

I have installed a fresh new raspiblitz and I have recovered CL with my old seed, all works as intended but in CL menu -> Seed it does not shows the seed.
![screenshot](https://user-images.githubusercontent.com/54238558/147143089-1e2a1b70-96be-4d02-a980-7604f658e9db.png)

I can see the seed with `sudo cat /home/bitcoin/.lightning/bitcoin/seedwords.info` since wallet is not encrypted but not from the CL menu

**Comment by Tracachang** [comment] 2021-12-22 23:16
When typing `sudo cat /home/bitcoin/.lightning/bitcoin/seedwords.info`. It shows:

`# This file was placed by cl.hsmtool.sh .
#Contains the seed words from which the hsm_secret in the same directory was generated
seedwords='word word word word word word word word word word word word word word word word word word word word word word word word'
seedwords6x4=''
#Will be removed safely when the hsm_secret is encrypted.
`

While in a new wallet created (appearing seed in CL-> Seed), the seedwords.info file looks like this (appearing seed twice, in seedwords= and in seedwords6x4):

`# This file was placed by cl.hsmtool.sh .
#Contains the seed words from which the hsm_secret in the same directory was generated
seedwords='word word word word word word word word word word word word word word word word word word word word word word word word'
seedwords6x4=''word word word word word word word word word word word word word word word word word word word word word word word word'
#Will be removed safely when the hsm_secret is encrypted.
`

**Comment by rootzoll** [comment] 2021-12-23 14:00
@openoms can you take a look

**Comment by openoms** [comment] 2021-12-23 14:28
thanks for reporting. the problem is the `cl.hsmtool.sh` does not create the `seedwords6x4` format.
due to fix

**Comment by rootzoll** [comment] 2022-02-17 16:43
OK closing this issue for v1.7.2 release.

**Closed as completed by rootzoll** 2022-02-17 16:43 UTC
