### ISSUE TITLE
Replace raspi case suggestion(does not fit)

### ISSUE THREAD

**Issue by daniel-vera-g** [raspiblitz/raspiblitz#265] opened 2019-01-10 17:15 UTC
In the description for the [Hardware Needed(Amazon shopping list)](https://github.com/rootzoll/raspiblitz#hardware-needed-amazon-shopping-list) this case is proposed:

* https://www.amazon.de/dp/B0173GQF8Y

After testing it and hearing other peoples experiences, I think it should be replaced.

1. For some people(including myself) the Pi did not really fit into the case.
2. Some larger Screens also do not fit with it

I am going to get a case without screen support since I don't really need one. That's the reason I don't have a new suggestion. Maybe someone can propose a better one.

Nevertheless great work with the tutorial, it's being really intuitive.

**Comment by rootzoll** [comment] 2019-01-13 23:14
I had over 10 of those cases in workshops and all Pis fitted OK.
The LCD in the shopping list also fits on the case (without the topping).

I am open for replacements (could be cheaper, prime shipping, german seller) - but the issue is not hot, so I close it for now.

**Closed as completed by rootzoll** 2019-01-13 23:14 UTC
