### ISSUE TITLE
RTL hangs on RPI idle

### ISSUE THREAD

**Issue by woeisme** [raspiblitz/raspiblitz#700] opened 2019-08-02 01:07 UTC
I've noticed several times now that when the Raspberry PI (4) is left running for a few hours that RTL webhost becomes unresponsive. It's only after moving the menu items around via ssh raspiblitz menu that RTL becomes accessible again and I can log in to it again. This is all via local wired home network.

**Comment by openoms** [comment] 2019-08-03 21:20
Are you saying saying that RTL runs fine after a restart and only after  a while becomes unresponsive?

Check what
 `sudo systemctl status RTL` 
shows then.
You  can restart just RTL with:
`sudo systemctl restart RTL`
and check if that helps.

I opened and issue with them because had a problem installing RTL on the latest build using an Odroid HC1. See here: https://github.com/ShahanaFarooqui/RTL/issues/173

**Comment by woeisme** [comment] 2019-08-03 22:21
it becomes unresponsive in the browser, merely moving the cursor around in the ssh menu (raspiblitz main menu) "wakes it up" and the web site becomes reachable again.

**Comment by openoms** [comment] 2019-08-06 13:47
> I've noticed several times now that when the Raspberry PI (4) is left running for a few hours that RTL webhost becomes unresponsive. It's only after moving the menu items around via ssh raspiblitz menu that RTL becomes accessible again and I can log in to it again. This is all via local wired home network.

Now I have made RTL work on the 1.3RC2 I can confirm this issue on my Odroid HC1. RTL website ws not respondig until I logged in via ssh (did not even need to get to the menu). Then works again. Running the latest RTL 0.4.4.

**Comment by nyxnor** [comment] 2021-04-18 07:20
Please close this.

**Closed as completed** 2021-04-19 13:57 UTC
