### ISSUE TITLE
Three RC2 suggestions

### ISSUE THREAD

**Issue by Csi18nAlistairMann** [raspiblitz/raspiblitz#2588] opened 2021-10-01 16:56 UTC
Nothing but these found from multiple attempts to clean install. Thanks!

1: After receiving blockchain from another RaspiBlitz, and receiving the "welcome new node operator!" messgae, recipient machine reported:
```
***********************************************************
RaspiBlitz going to reboot
***********************************************************
SSH again into system with:
ssh admin@192.168.1.112
***********************************************************
admin@raspberrypi:~ $ 
```
uptime(1) revealed no reboot occurred as of ten hours after.
I suggest message be removed and process changed to return user to 00raspblitz.sh

2: Copy menu item says
```
COPY      Copy from Computer/RaspiBlitz over LAN (±6h)
```
I saw it take 2.5 hrs through a 1Gbps switch, and 10 hrs through a 100Mbps switch, so that "±" is doing alot of work.
I suggest "±6h" be changed to "3-10h"

3: There is an alert on shutdown that reads
```
LCD turns white when shutdown complete.
```
I suggest EITHER it would be better to read
```
Green activity light stays dark and LCD turns white when shutdown complete
```
OR leave it the same and add a FAQ entry "How can I tell when my RaspiBlitz is off?"

**Comment by rootzoll** [comment] 2021-10-04 07:59
1) The reboot is needed to finish the setup ... if it didnt went into reboot thats a bug. On my test machines its rebooting - so I cannot reproduce - but I put a enforcement of the reboot into the script. Will be part of RC3 that will be released within the next days. Please let us know if this this still happening of your machine with the RC3.

2) updated

3) updated

**Closed as completed** 2021-10-04 10:32 UTC
