### ISSUE TITLE
boot from SSD

### ISSUE THREAD

**Issue by G0ld-Asp3ct** [raspiblitz/raspiblitz#1325] opened 2020-07-09 09:08 UTC
making the Raspiblitz able to boot from SSD per USB would be more reliable and faster.
SD Cards breaks pretty fast and setting up the Blitz again isn't user friendly (DAU's doesn't do backups)

**Comment by openoms** [comment] 2020-07-09 10:16
duplicate of https://github.com/rootzoll/raspiblitz/issues/1235 closing.

**Closed as completed by openoms** 2020-07-09 10:16 UTC
