### ISSUE TITLE
Raspiblitz 1.4

### ISSUE THREAD

**Issue by BTCxZelko** [raspiblitz/raspiblitz#972] opened 2020-01-12 06:19 UTC
During initial setup..hdd.sh failed to find my hdd and mount, continued to hang. I manually added and started again. This fixed issue.

Separate issue: Started torrent download IBD...trying to login via admin@IPaddress. I get a connection closed by IPaddress on port 22

LCD screen displays my IP address and log in instructions as it should. Not sure of a work around. I'll try ssh from different device

**Comment by rootzoll** [comment] 2020-01-22 21:46
Thanks for the report - the RC2 had problems with detecting the hdd - this should be fixed now. Test running good. Was not able to reproduce the ssh failing login. Closing issue.

**Closed as completed by rootzoll** 2020-01-22 21:46 UTC
