### ISSUE TITLE
Add Jamapp

### ISSUE THREAD

**Issue by Sep21-2009** [raspiblitz/raspiblitz#3392] opened 2022-10-28 19:18 UTC
Please add Jamapp 

If I follow the instructions then the node crashes for me.  then there is always ngnix error!
https://jamdocs.org/software/installation/#with-raspiblitz

https://github.com/joinmarket-webui/jam/releases

https://jamapp.org/

**Comment by openoms** [comment] 2022-10-28 19:51
Adding in https://github.com/rootzoll/raspiblitz/pull/3321

Closing as duplicate of https://github.com/rootzoll/raspiblitz/issues/2891

**Closed as completed by openoms** 2022-10-28 19:51 UTC
