### ISSUE TITLE
Can't Connect Fully Noded IOS

### ISSUE THREAD

**Issue by doccodez** [raspiblitz/raspiblitz#2469] opened 2021-08-10 01:48 UTC
When I use the QR code to connect fully noded to my rapiblitz node it tells me "Looks like your node is not on, make sure it is running and try again." ??

**Comment by openoms** [comment] 2021-08-10 07:54
Duplicate of this issue with the fix detailed: https://github.com/rootzoll/raspiblitz/issues/2339#issuecomment-860166987

**Closed as completed by openoms** 2021-08-10 07:54 UTC
