### ISSUE TITLE
error code: -28 error message: Loading block index...

### ISSUE THREAD

**Issue by grnqrtr** [raspiblitz/raspiblitz#1466] opened 2020-08-19 14:02 UTC
I get this on every reboot and and I've seen a number of other people get this on 1.6. Seems like it is giving up to early or something, doesn't give enough time to let the block index load.
```
*****************************************
* The bitcoind service is not running.
*****************************************
If you just started some config/setup, this might be OK.

More Error Detail:
error code: -28 error message: Loading block index...

POSSIBLE OPTIONS:
-> Use command 'repair' and then choose 'DELETE-INDEX' to try rebuilding transaction index.
-> Use command 'repair' and then choose 'RESET-CHAIN' to try downloading new blockchain.
-> Use command 'debug' for more log output you can use for getting support.
-> Use command 'menu' to open main menu.
-> Have you tried to turn it off and on again? Use command 'restart'

bitcoin error: error code: -28
error message:
Loading block index...
```

**Comment by ChuckNorrison** [comment] 2020-08-19 21:57
hey i get this too after power off and on. last reboot it worked. Everytime if that happens, i have to update public ip manually with the dynupdate url

**Comment by Jestopher-BTC** [comment] 2020-08-19 22:41
Just got this error with a completely fresh SD.

**Comment by bitsam** [comment] 2020-08-20 00:03
run, sudo tail -n 20 /mnt/hdd/bitcoin/debug.log

See if it is slowly verifying the blocks or downloading blocks. Once the chain is sync'd then you can run , raspiblitz to launch the menu and go back through the normal loading without a reboot. 

I also find running the lnd wallet unlock to help with the command, lncli unlock

**Comment by bitsam** [comment] 2020-08-20 00:06
I had some teething problems with 1.6, and decided to blow away the chain data. Which was probably an over-reaction, as once I had finally copied it over I still got the above errors, and it was caused by the the slow verification of blocks or need to download the last few remaining blocks while the node had been offline. You can check all this in the /bitcoin/debug.log

**Comment by ChuckNorrison** [comment] 2020-08-20 19:15
so its just a race condition between the bitcoind and lnd. Wait for start lnd while bitcoind is syncing. Not that easy for a script to get that state i think, if it depends a lot on sync time... can be seconds, days or weeks. At setup from scratch that all worked well.

Further in my cases there was no need to interact... the LND waits in a suspend state or something as i observed. So only wait for the bitcoind sync progress. that could be visualized a bit more

**Comment by rootzoll** [comment] 2020-08-24 15:59
This seems to be a timing issue .. marked for v1.6.1 to change timing on this.

**Comment by thecharacter** [comment] 2020-08-30 04:12
I figured out a workaround if you type menu in the Commandline then select Info from the menu options it will ask you to type in your LND password and then the load index window will appear letting you know what percentage your Blockchain Index and LND index is at.

**Comment by rootzoll** [comment] 2020-09-02 16:57
merged the fix by @CandleHater - putting it on final testing

**Comment by rootzoll** [comment] 2020-09-03 11:33
original fix by @CandleHater tested good .. rolling with that.

**Comment by rootzoll** [comment] 2020-10-08 15:05
Tested for some weeks now ... looks good. Will be part of v1.6.1. Closing this issue.

**Closed as completed by rootzoll** 2020-10-08 15:05 UTC
