### ISSUE TITLE
LND disabled, 00infoLCD.sh runs 80scanLND

### ISSUE THREAD

**Issue by pg024** [raspiblitz/raspiblitz#611] opened 2019-05-16 22:03 UTC
Hello, I have disabled the LND service through systemctl.

On the raspberry LCD display it looks like that 80scanLND.sh is running, showing SSH credentials and the remainder "LND is not running" whereas it should run 00infoBlitz.sh instead maybe?

**Workaround**
Comment out this par on 00infoLCD.sh .

`  if LND is syncing or scanning`
 ` lndSynced=$(sudo -u bitcoin /usr/local/bin/lncli --chain=${network} --netw$`
 `  if [ ${lndSynced} -eq 0 ]; then`
`     /home/admin/80scanLND.sh`
  `   sleep 20`
`    continue`
`  fi`

**Comment by openoms** [comment] 2019-05-17 12:46
Hi, sorry it is not clear what are you trying to achieve here.
Re-enable LND and the issue is solved.

**Comment by fluidvoice** [comment] 2019-05-19 11:32
If your goal is to make running LND optional, that is not the goal of this Raspiblitz project, so you'll have to learn all about the scripts and modify them yourself.  Please close this issue.

**Closed as completed** 2019-05-19 12:06 UTC
