### ISSUE TITLE
1.7.2rc2 - Fresh Sync Wrong Progress Indication

### ISSUE THREAD

**Issue by mrsieb** [raspiblitz/raspiblitz#2961] opened 2022-02-14 18:34 UTC
On a fresh sync the progress Number looks strange, and counts down starting from 100000%

![image](https://user-images.githubusercontent.com/1194346/153924928-46ffdd9a-b446-4d59-ad00-4d0e9090b0f0.png)
![image](https://user-images.githubusercontent.com/1194346/153925111-48470490-c56e-451b-8119-7d9470674b0c.png)

**Comment by mrsieb** [comment] 2022-02-16 11:49
After sync is complete everything looks good, its just  during sync.

**Comment by rootzoll** [comment] 2022-02-16 21:04
Thanks for the report - will check if I can reproduce.

**Comment by rootzoll** [comment] 2022-02-16 23:05
I did a setup of a fresh sync and number look OK - so I was not able to reproduce this. I leave this issue open as unconfirmed until the v1.8 release for anybody to report this seeing the same.

**Comment by rootzoll** [comment] 2022-05-09 21:25
Did not got further reports on this. Closing for now.

**Closed as completed by rootzoll** 2022-05-09 21:25 UTC
Labels: bug - unconfirmed
