### ISSUE TITLE
Blockchain progress stuck at zero percent

### ISSUE THREAD

**Issue by jstrauss501** [raspiblitz/raspiblitz#2730] opened 2021-11-21 17:04 UTC
it seems like the blockchain sync process stucks. I have reboot many times already. can someone please help me solve the issues.

=======
![Screenshot from 2021-11-21 11-48-15](https://user-images.githubusercontent.com/94798007/142771783-fac06377-50bf-42e7-be34-12ed4483d1b6.png)
============================================
cat raspiblitz.log

***********************************************
Running RaspiBlitz Bootstrap 1.7.1
Sun 21 Nov 03:25:57 GMT 2021
***********************************************
# *** blitz.ssh.sh checkrepair
# countKeyFiles(8)
# OK: SSHD RUNNING
No HDMI switch found. 
No FS EXPAND needed. needsExpansion(0) fsexpanded(1)
No SSHRESET switch found. 
No UASP FIX needed (1st-try).
Waiting for HDD/SSD ...
total 604
drwxr-xr-x   2 root root   4096 Oct 28 11:00 .
drwxr-xr-x 118 root root   4096 Nov 20 01:12 ..
-rw-r--r--   1 root root 565189 Jan 31  2020 moduli
-rw-r--r--   1 root root   1580 Jan 31  2020 ssh_config
-rw-r--r--   1 root root   3250 Jan 31  2020 sshd_config
-rw-------   1 root root   1385 Oct 28 11:00 ssh_host_dsa_key
-rw-r--r--   1 root root    606 Oct 28 11:00 ssh_host_dsa_key.pub
-rw-------   1 root root    513 Oct 28 11:00 ssh_host_ecdsa_key
-rw-r--r--   1 root root    178 Oct 28 11:00 ssh_host_ecdsa_key.pub
-rw-------   1 root root    411 Oct 28 11:00 ssh_host_ed25519_key
-rw-r--r--   1 root root     98 Oct 28 11:00 ssh_host_ed25519_key.pub
-rw-------   1 root root   1823 Oct 28 11:00 ssh_host_rsa_key
-rw-r--r--   1 root root    398 Oct 28 11:00 ssh_host_rsa_key.pub
-rw-r--r--   1 root root    338 Mar  5  2021 ssh_import_id
wifiIsSet=0
hddBackupLocationAvailable=1
hddRestoreConfigAvailable=0
memRestoreConfigAvailable=0
wifiRestore=0
wifiBackup=0
No UASP FIX needed (2nd-try).
isMounted: 1
Skipping UASP deactivation ... cmdlineExists(1) hddAdapterUSB() hddAdapterUSAP(0)
HDD already part of system: 1
load configfile data
running LND users credentials update
###### SYNCING MACAROONS, RPC Password AND TLS Certificate ######
# make sure LND app-data directories exist

# copy macaroons to central app-data directory and ensure unix ownerships and permissions
# make sure admin has a symlink at ~/.lnd to /mnt/hdd/app-data/lnd/
# make sure LND conf is readable and symlinked
# make sure TLS certificate is readable and symlinked
Checking if additional backup device is configured .. ()
No additional backup device was configured.
CLEANING TEMP DRIVE/FOLDER
OK: Temp cleaned
DONE BOOTSTRAP

================================================
cat raspiblitz.provision-setup.log

###################################
# _provision.setup.sh
###################################
*** Prepare bitcoin ***
mkdir: cannot create directory ‘/mnt/hdd/bitcoin’: File exists
File Exists: /mnt/hdd/bitcoin/bitcoin.conf --> 1
# setting PASSWORD B
# OK -> RPC Password B changed
# Reboot is needed
...
*** Start bitcoin (SETUP) ***
- This can take a while ..
# (0/50) checking if bitcoind is running ... 
# (1/50) checking if bitcoind is running ... 
OK bitcoin startup successful 
Prepare Lightning (lnd)
############## Setup LND
Creating new LND config ...
*** Init LND Service & Start ***
Starting LND Service ...
WALLET --> NEW
*** Copy LND Macaroons to user admin ***
###### SYNCING MACAROONS, RPC Password AND TLS Certificate ######
# make sure LND app-data directories exist

# copy macaroons to central app-data directory and ensure unix ownerships and permissions
# make sure admin has a symlink at ~/.lnd to /mnt/hdd/app-data/lnd/
# make sure LND conf is readable and symlinked
# make sure TLS certificate is readable and symlinked
END Setup

=======================================

cat systemd.lightning.log | grep -i ERROR
1637467738 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637470100 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637473067 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637473794 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637473976 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637474703 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637480394 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637480576 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637482030 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637484391 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637484755 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637485118 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637485300 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637486027 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637486208 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637486390 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637486935 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637487117 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637490205 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637490568 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637491294 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637492021 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637492203 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637495290 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637495654 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637496017 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637496381 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637496562 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637511211 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637513692 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data

=====================================
cat systemd.lightning.log 
SYSTEMD RESTART LOG: lightning (LND)
1637467010 STARTED
1637467071 STARTED
1637467131 STARTED
1637467192 STARTED
1637467253 STARTED
1637467313 STARTED
1637467374 STARTED
1637467434 STARTED
1637467495 STARTED
1637467555 STARTED
1637467616 STARTED
1637467676 STARTED
1637467737 STARTED
1637467738 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637467798 STARTED
1637467858 STARTED
1637467919 STARTED
1637467979 STARTED
1637468040 STARTED
1637468100 STARTED
1637468161 STARTED
1637468221 STARTED
1637468282 STARTED
1637468342 STARTED
1637468403 STARTED
1637468463 STARTED
1637468524 STARTED
1637468584 STARTED
1637468645 STARTED
1637468705 STARTED
1637468766 STARTED
1637468827 STARTED
1637468887 STARTED
1637468948 STARTED
1637469008 STARTED
1637469069 STARTED
1637469129 STARTED
1637469190 STARTED
1637469250 STARTED
1637469311 STARTED
1637469372 STARTED
1637469432 STARTED
1637469493 STARTED
1637469554 STARTED
1637469614 STARTED
1637469675 STARTED
1637469736 STARTED
1637469796 STARTED
1637469857 STARTED
1637469917 STARTED
1637469978 STARTED
1637470038 STARTED
1637470099 STARTED
1637470100 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637470160 STARTED
1637470220 STARTED
1637470281 STARTED
1637470342 STARTED
1637470402 STARTED
1637470463 STARTED
1637470523 STARTED
1637470584 STARTED
1637470644 STARTED
1637470705 STARTED
1637470765 STARTED
1637470826 STARTED
1637470886 STARTED
1637470947 STARTED
1637471008 STARTED
1637471068 STARTED
1637471129 STARTED
1637471189 STARTED
1637471250 STARTED
1637471310 STARTED
1637471371 STARTED
1637471431 STARTED
1637471492 STARTED
1637471552 STARTED
1637471613 STARTED
1637471673 STARTED
1637471734 STARTED
1637471795 STARTED
1637471855 STARTED
1637471916 STARTED
1637471976 STARTED
1637472037 STARTED
1637472098 STARTED
1637472158 STARTED
1637472219 STARTED
1637472280 STARTED
1637472340 STARTED
1637472401 STARTED
1637472461 STARTED
1637472522 STARTED
1637472582 STARTED
1637472643 STARTED
1637472703 STARTED
1637472764 STARTED
1637472824 STARTED
1637472885 STARTED
1637472945 STARTED
1637473006 STARTED
1637473067 STARTED
1637473067 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637473127 STARTED
1637473188 STARTED
1637473249 STARTED
1637473309 STARTED
1637473370 STARTED
1637473430 STARTED
1637473491 STARTED
1637473551 STARTED
1637473612 STARTED
1637473672 STARTED
1637473733 STARTED
1637473793 STARTED
1637473794 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637473854 STARTED
1637473915 STARTED
1637473975 STARTED
1637473976 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637474036 STARTED
1637474096 STARTED
1637474157 STARTED
1637474218 STARTED
1637474278 STARTED
1637474339 STARTED
1637474399 STARTED
1637474460 STARTED
1637474520 STARTED
1637474581 STARTED
1637474641 STARTED
1637474702 STARTED
1637474703 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637474763 STARTED
1637474823 STARTED
1637474884 STARTED
1637474945 STARTED
1637475005 STARTED
1637475066 STARTED
1637475126 STARTED
1637475187 STARTED
1637475248 STARTED
1637475308 STARTED
1637475369 STARTED
1637475429 STARTED
1637475490 STARTED
1637475551 STARTED
1637475611 STARTED
1637475672 STARTED
1637475732 STARTED
1637475793 STARTED
1637475853 STARTED
1637475914 STARTED
1637475974 STARTED
1637476035 STARTED
1637476095 STARTED
1637476156 STARTED
1637476216 STARTED
1637476277 STARTED
1637476337 STARTED
1637476398 STARTED
1637476458 STARTED
1637476519 STARTED
1637476579 STARTED
1637476640 STARTED
1637476700 STARTED
1637476761 STARTED
1637476821 STARTED
1637476882 STARTED
1637476943 STARTED
1637477003 STARTED
1637477064 STARTED
1637477125 STARTED
1637477185 STARTED
1637477246 STARTED
1637477306 STARTED
1637477367 STARTED
1637477427 STARTED
1637477488 STARTED
1637477548 STARTED
1637477609 STARTED
1637477669 STARTED
1637477730 STARTED
1637477790 STARTED
1637477851 STARTED
1637477911 STARTED
1637477972 STARTED
1637478032 STARTED
1637478093 STARTED
1637478154 STARTED
1637478214 STARTED
1637478275 STARTED
1637478335 STARTED
1637478396 STARTED
1637478456 STARTED
1637478517 STARTED
1637478577 STARTED
1637478638 STARTED
1637478698 STARTED
1637478759 STARTED
1637478819 STARTED
1637478880 STARTED
1637478940 STARTED
1637479001 STARTED
1637479061 STARTED
1637479122 STARTED
1637479182 STARTED
1637479243 STARTED
1637479303 STARTED
1637479364 STARTED
1637479424 STARTED
1637479485 STARTED
1637479546 STARTED
1637479606 STARTED
1637479667 STARTED
1637479727 STARTED
1637479788 STARTED
1637479848 STARTED
1637479909 STARTED
1637479969 STARTED
1637480030 STARTED
1637480091 STARTED
1637480151 STARTED
1637480212 STARTED
1637480272 STARTED
1637480333 STARTED
1637480393 STARTED
1637480394 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637480454 STARTED
1637480515 STARTED
1637480575 STARTED
1637480576 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637480636 STARTED
1637480696 STARTED
1637480757 STARTED
1637480818 STARTED
1637480878 STARTED
1637480939 STARTED
1637480999 STARTED
1637481060 STARTED
1637481120 STARTED
1637481181 STARTED
1637481241 STARTED
1637481302 STARTED
1637481363 STARTED
1637481423 STARTED
1637481484 STARTED
1637481544 STARTED
1637481605 STARTED
1637481665 STARTED
1637481726 STARTED
1637481786 STARTED
1637481847 STARTED
1637481908 STARTED
1637481968 STARTED
1637482029 STARTED
1637482030 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637482089 STARTED
1637482150 STARTED
1637482210 STARTED
1637482271 STARTED
1637482332 STARTED
1637482392 STARTED
1637482453 STARTED
1637482513 STARTED
1637482574 STARTED
1637482634 STARTED
1637482695 STARTED
1637482755 STARTED
1637482816 STARTED
1637482876 STARTED
1637482937 STARTED
1637482997 STARTED
1637483058 STARTED
1637483118 STARTED
1637483179 STARTED
1637483239 STARTED
1637483300 STARTED
1637483360 STARTED
1637483421 STARTED
1637483481 STARTED
1637483542 STARTED
1637483603 STARTED
1637483663 STARTED
1637483724 STARTED
1637483784 STARTED
1637483845 STARTED
1637483905 STARTED
1637483966 STARTED
1637484027 STARTED
1637484087 STARTED
1637484148 STARTED
1637484209 STARTED
1637484269 STARTED
1637484330 STARTED
1637484390 STARTED
1637484391 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637484451 STARTED
1637484512 STARTED
1637484572 STARTED
1637484633 STARTED
1637484693 STARTED
1637484754 STARTED
1637484755 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637484815 STARTED
1637484875 STARTED
1637484936 STARTED
1637484996 STARTED
1637485057 STARTED
1637485117 STARTED
1637485118 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637485178 STARTED
1637485239 STARTED
1637485299 STARTED
1637485300 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637485360 STARTED
1637485420 STARTED
1637485481 STARTED
1637485542 STARTED
1637485602 STARTED
1637485663 STARTED
1637485723 STARTED
1637485784 STARTED
1637485844 STARTED
1637485905 STARTED
1637485965 STARTED
1637486026 STARTED
1637486027 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637486087 STARTED
1637486147 STARTED
1637486208 STARTED
1637486208 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637486268 STARTED
1637486329 STARTED
1637486389 STARTED
1637486390 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637486450 STARTED
1637486510 STARTED
1637486571 STARTED
1637486632 STARTED
1637486692 STARTED
1637486753 STARTED
1637486813 STARTED
1637486874 STARTED
1637486935 STARTED
1637486935 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637486995 STARTED
1637487056 STARTED
1637487117 STARTED
1637487117 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637487177 STARTED
1637487238 STARTED
1637487298 STARTED
1637487359 STARTED
1637487419 STARTED
1637487480 STARTED
1637487540 STARTED
1637487601 STARTED
1637487662 STARTED
1637487722 STARTED
1637487783 STARTED
1637487843 STARTED
1637487904 STARTED
1637487965 STARTED
1637488025 STARTED
1637488086 STARTED
1637488146 STARTED
1637488207 STARTED
1637488267 STARTED
1637488328 STARTED
1637488388 STARTED
1637488449 STARTED
1637488509 STARTED
1637488570 STARTED
1637488630 STARTED
1637488691 STARTED
1637488751 STARTED
1637488812 STARTED
1637488872 STARTED
1637488933 STARTED
1637488993 STARTED
1637489054 STARTED
1637489114 STARTED
1637489175 STARTED
1637489235 STARTED
1637489296 STARTED
1637489357 STARTED
1637489417 STARTED
1637489478 STARTED
1637489538 STARTED
1637489599 STARTED
1637489659 STARTED
1637489720 STARTED
1637489780 STARTED
1637489841 STARTED
1637489902 STARTED
1637489962 STARTED
1637490023 STARTED
1637490083 STARTED
1637490144 STARTED
1637490204 STARTED
1637490205 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637490265 STARTED
1637490325 STARTED
1637490386 STARTED
1637490446 STARTED
1637490507 STARTED
1637490567 STARTED
1637490568 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637490628 STARTED
1637490688 STARTED
1637490749 STARTED
1637490809 STARTED
1637490870 STARTED
1637490930 STARTED
1637490991 STARTED
1637491051 STARTED
1637491112 STARTED
1637491172 STARTED
1637491233 STARTED
1637491293 STARTED
1637491294 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637491354 STARTED
1637491415 STARTED
1637491475 STARTED
1637491536 STARTED
1637491596 STARTED
1637491657 STARTED
1637491717 STARTED
1637491778 STARTED
1637491838 STARTED
1637491899 STARTED
1637491960 STARTED
1637492020 STARTED
1637492021 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637492081 STARTED
1637492141 STARTED
1637492202 STARTED
1637492203 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637492263 STARTED
1637492323 STARTED
1637492384 STARTED
1637492444 STARTED
1637492505 STARTED
1637492565 STARTED
1637492626 STARTED
1637492686 STARTED
1637492747 STARTED
1637492807 STARTED
1637492868 STARTED
1637492928 STARTED
1637492989 STARTED
1637493049 STARTED
1637493110 STARTED
1637493170 STARTED
1637493231 STARTED
1637493292 STARTED
1637493352 STARTED
1637493413 STARTED
1637493473 STARTED
1637493534 STARTED
1637493594 STARTED
1637493655 STARTED
1637493715 STARTED
1637493776 STARTED
1637493836 STARTED
1637493897 STARTED
1637493957 STARTED
1637494018 STARTED
1637494078 STARTED
1637494139 STARTED
1637494200 STARTED
1637494260 STARTED
1637494321 STARTED
1637494381 STARTED
1637494442 STARTED
1637494502 STARTED
1637494563 STARTED
1637494624 STARTED
1637494684 STARTED
1637494745 STARTED
1637494805 STARTED
1637494866 STARTED
1637494926 STARTED
1637494987 STARTED
1637495047 STARTED
1637495108 STARTED
1637495168 STARTED
1637495229 STARTED
1637495290 STARTED
1637495290 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637495350 STARTED
1637495411 STARTED
1637495471 STARTED
1637495532 STARTED
1637495592 STARTED
1637495653 STARTED
1637495654 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637495714 STARTED
1637495774 STARTED
1637495835 STARTED
1637495896 STARTED
1637495956 STARTED
1637496017 STARTED
1637496017 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637496077 STARTED
1637496138 STARTED
1637496198 STARTED
1637496259 STARTED
1637496319 STARTED
1637496380 STARTED
1637496381 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637496441 STARTED
1637496501 STARTED
1637496562 STARTED
1637496562 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637496622 STARTED
1637496683 STARTED
1637496743 STARTED
1637496804 STARTED
1637496864 STARTED
1637496925 STARTED
1637496985 STARTED
1637497046 STARTED
1637497106 STARTED
1637497167 STARTED
1637497227 STARTED
1637497288 STARTED
1637497348 STARTED
1637497409 STARTED
1637497469 STARTED
1637497530 STARTED
1637497590 STARTED
1637497651 STARTED
1637497711 STARTED
1637497772 STARTED
1637497832 STARTED
1637497893 STARTED
1637497953 STARTED
1637498014 STARTED
1637498074 STARTED
1637498135 STARTED
1637498195 STARTED
1637498256 STARTED
1637498316 STARTED
1637498377 STARTED
1637498437 STARTED
1637498498 STARTED
1637498559 STARTED
1637498619 STARTED
1637498680 STARTED
1637498740 STARTED
1637498801 STARTED
1637498862 STARTED
1637498922 STARTED
1637498983 STARTED
1637499043 STARTED
1637499104 STARTED
1637499164 STARTED
1637499225 STARTED
1637499285 STARTED
1637499346 STARTED
1637499406 STARTED
1637499467 STARTED
1637499527 STARTED
1637499588 STARTED
1637499648 STARTED
1637499709 STARTED
1637499769 STARTED
1637499830 STARTED
1637499890 STARTED
1637499951 STARTED
1637500011 STARTED
1637500072 STARTED
1637500133 STARTED
1637500193 STARTED
1637500254 STARTED
1637500314 STARTED
1637500375 STARTED
1637500435 STARTED
1637500496 STARTED
1637500557 STARTED
1637500617 STARTED
1637500678 STARTED
1637500738 STARTED
1637500799 STARTED
1637500859 STARTED
1637500920 STARTED
1637500980 STARTED
1637501041 STARTED
1637501101 STARTED
1637501162 STARTED
1637501222 STARTED
1637501283 STARTED
1637501343 STARTED
1637501404 STARTED
1637501464 STARTED
1637501525 STARTED
1637501586 STARTED
1637501646 STARTED
1637501707 STARTED
1637501767 STARTED
1637501828 STARTED
1637501888 STARTED
1637501949 STARTED
1637502009 STARTED
1637502070 STARTED
1637502130 STARTED
1637502191 STARTED
1637502251 STARTED
1637502312 STARTED
1637502372 STARTED
1637502433 STARTED
1637502494 STARTED
1637502554 STARTED
1637502615 STARTED
1637502675 STARTED
1637502736 STARTED
1637502796 STARTED
1637502857 STARTED
1637502917 STARTED
1637502978 STARTED
1637503038 STARTED
1637503099 STARTED
1637503159 STARTED
1637503220 STARTED
1637503281 STARTED
1637503341 STARTED
1637503402 STARTED
1637503462 STARTED
1637503523 STARTED
1637503583 STARTED
1637503644 STARTED
1637503704 STARTED
1637503765 STARTED
1637503825 STARTED
1637503886 STARTED
1637503946 STARTED
1637504007 STARTED
1637504067 STARTED
1637504128 STARTED
1637504188 STARTED
1637504249 STARTED
1637504309 STARTED
1637504370 STARTED
1637504430 STARTED
1637504491 STARTED
1637504551 STARTED
1637504612 STARTED
1637504672 STARTED
1637504733 STARTED
1637504794 STARTED
1637504854 STARTED
1637504915 STARTED
1637504975 STARTED
1637505036 STARTED
1637505096 STARTED
1637505157 STARTED
1637505217 STARTED
1637505278 STARTED
1637505338 STARTED
1637505399 STARTED
1637505459 STARTED
1637505520 STARTED
1637505580 STARTED
1637505641 STARTED
1637505701 STARTED
1637505762 STARTED
1637505823 STARTED
1637505883 STARTED
1637505944 STARTED
1637506004 STARTED
1637506065 STARTED
1637506125 STARTED
1637506186 STARTED
1637506246 STARTED
1637506307 STARTED
1637506368 STARTED
1637506428 STARTED
1637506489 STARTED
1637506549 STARTED
1637506610 STARTED
1637506670 STARTED
1637506731 STARTED
1637506791 STARTED
1637506852 STARTED
1637506912 STARTED
1637506973 STARTED
1637507033 STARTED
1637507094 STARTED
1637507155 STARTED
1637507215 STARTED
1637507276 STARTED
1637507336 STARTED
1637507397 STARTED
1637507457 STARTED
1637507518 STARTED
1637507579 STARTED
1637507639 STARTED
1637507700 STARTED
1637507760 STARTED
1637507821 STARTED
1637507881 STARTED
1637507942 STARTED
1637508002 STARTED
1637508063 STARTED
1637508123 STARTED
1637508184 STARTED
1637508244 STARTED
1637508305 STARTED
1637508365 STARTED
1637508426 STARTED
1637508486 STARTED
1637508547 STARTED
1637508608 STARTED
1637508668 STARTED
1637508729 STARTED
1637508789 STARTED
1637508850 STARTED
1637508910 STARTED
1637508971 STARTED
1637509031 STARTED
1637509092 STARTED
1637509152 STARTED
1637509213 STARTED
1637509273 STARTED
1637509334 STARTED
1637509394 STARTED
1637509455 STARTED
1637509515 STARTED
1637509576 STARTED
1637509637 STARTED
1637509697 STARTED
1637509758 STARTED
1637509818 STARTED
1637509879 STARTED
1637509939 STARTED
1637510000 STARTED
1637510061 STARTED
1637510121 STARTED
1637510182 STARTED
1637510242 STARTED
1637510303 STARTED
1637510363 STARTED
1637510424 STARTED
1637510484 STARTED
1637510545 STARTED
1637510605 STARTED
1637510666 STARTED
1637510726 STARTED
1637510787 STARTED
1637510847 STARTED
1637510908 STARTED
1637510968 STARTED
1637511029 STARTED
1637511089 STARTED
1637511150 STARTED
1637511210 STARTED
1637511211 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637511271 STARTED
1637511332 STARTED
1637511392 STARTED
1637511453 STARTED
1637511513 STARTED
1637511574 STARTED
1637511634 STARTED
1637511695 STARTED
1637511755 STARTED
1637511816 STARTED
1637511876 STARTED
1637511937 STARTED
1637511997 STARTED
1637512058 STARTED
1637512118 STARTED
1637512179 STARTED
1637512239 STARTED
1637512300 STARTED
1637512360 STARTED
1637512421 STARTED
1637512481 STARTED
1637512542 STARTED
1637512602 STARTED
1637512663 STARTED
1637512723 STARTED
1637512784 STARTED
1637512845 STARTED
1637512905 STARTED
1637512966 STARTED
1637513026 STARTED
1637513087 STARTED
1637513147 STARTED
1637513208 STARTED
1637513268 STARTED
1637513329 STARTED
1637513389 STARTED
1637513450 STARTED
1637513510 STARTED
1637513571 STARTED
1637513631 STARTED
1637513692 STARTED
1637513692 ERROR: [lncli] could not load global options: unable to decode macaroon: empty macaroon data
1637513752 STARTED
1637513813 STARTED
1637513873 STARTED
1637513934 STARTED

**Comment by rootzoll** [comment] 2021-11-25 21:32
I dont think in your case the problem is with the lightning part ... something seems to be off with bitcoind that makes lnd restart a lot of times. If this is a fresh setup I would recommend starting fresh again. Turn everything off, flash a new sd card and during then dont choose `recover` do with fresh setup and dont delete the HDD/SSD when asked (dont reuse blockchain). 

If you run into the same problem, please write again.

**Comment by rootzoll** [comment] 2021-11-30 23:04
Closing this issue .. please reopen if problem still exists.

**Closed as completed by rootzoll** 2021-11-30 23:04 UTC
