### ISSUE TITLE
WebUI Dashboard does not load owith fresh CLN install

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#3793] opened 2023-05-05 10:49 UTC
Installed a fresh CLN with v1.9.0rc4 .. but after setup the Dashboard does not load (infinite waiting) - while on LCD display CLN looks ready:

![Bildschirmfoto 2023-05-05 um 12 46 40](https://user-images.githubusercontent.com/2472225/236438384-1b1344ae-c3d4-4f3d-90cb-a581a82d3951.png)

**Comment by cstenglein** [comment] 2023-05-09 05:27
Duplicate of #3807 ?

**Comment by rootzoll** [comment] 2023-05-10 13:46
OK this worked now on a test. Cloing for v1.9.0rc5

**Closed as completed** 2023-05-10 13:46 UTC
