### ISSUE TITLE
LND Locked after update from v1.1 to v1.2

### ISSUE THREAD

**Issue by inpharmaticist** [raspiblitz/raspiblitz#642] opened 2019-06-03 23:57 UTC
Debug output:
https://termbin.com/22p9

**Comment by fluidvoice** [comment] 2019-06-04 00:29
Did you unlock the wallet? Did you wait for the blockchain sync to finish?

**Comment by inpharmaticist** [comment] 2019-06-04 00:35
Yes, it says it unlocked, then asks for password again, then says it may be stuck in a loop.

![image](https://user-images.githubusercontent.com/49789899/58843074-d1021f80-8625-11e9-83e7-05747b877ce6.png)

It may be because I tried to install EPS and the guide had me make some edits to the bitcoin and lnd config files. EPS didn't work (newb). But the node still worked until I tried to update raspiblitz.

**Comment by fluidvoice** [comment] 2019-06-04 01:31
wait until bitcoin is fully synced, then unlock the wallet.  If it still doesn't work run this:
`sudo cat /mnt/hdd/bitcoin/debug.log | nc termbin.com 9999`
`sudo cat /var/log/syslog | nc termbin.com 9999`

**Comment by inpharmaticist** [comment] 2019-06-04 14:55
Bitcoin is synced, I did run that and pasted it in my first comment. Here it is again:

Debug output:
https://termbin.com/22p9

**Comment by inpharmaticist** [comment] 2019-06-05 05:37
I now notice the bitcoin.conf file is empty. Not sure if the v1.2 update did this. Can the node operate if this file is blank?

**Comment by rootzoll** [comment] 2019-06-05 10:41
The bitcoin.conf being empty is a bug - to be fixed in next version. Please fil lthe file again with data from this template with adding your personal rpcpassword (password B):
https://github.com/rootzoll/raspiblitz/blob/master/home.admin/assets/bitcoin.conf

**Comment by fluidvoice** [comment] 2019-06-07 03:03
> Bitcoin is synced, I did run that and pasted it in my first comment. Here it is again:
> 
> Debug output:
> https://termbin.com/22p9

I didn't ask you to re-send the same log output again. I asked you to post **new** logging after you were synced and unlocked your wallet.
Additionally I asked you to post the contents of your `syslog` file.  This can often show system problems.
But anyway, it looks like the problem is the empty bitcoin.conf file.  But that might be just a symptom of something else wrong.

**Comment by inpharmaticist** [comment] 2019-06-07 04:12
@fluidvoice My bad, didn't realize you needed an updated log. @rootzoll that seemed to do the trick. Thanks both of you!

**Closed as completed** 2019-06-07 04:13 UTC
